name: Run all CI tests
on: [pull_request, push]

jobs:
  run_all_tests:
    runs-on: ubuntu-latest
    name: Full CI (style and tests)
    container: jcsda/docker-gnu-openmpi-dev:1.9
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: i-jedi
        submodules: recursive
    - name: Get dependency commit hashes
      id: dep-hashes
      shell: bash
      run: |
        set -e
        echo "oops=$(git ls-remote https://github.com/NOAA-EMC/oops.git feature/mist | cut -f1)" >> $GITHUB_OUTPUT
        echo "vader=$(git ls-remote https://github.com/JCSDA/vader.git develop | cut -f1)" >> $GITHUB_OUTPUT
        mkdir -p $GITHUB_WORKSPACE/Build/lib
        mkdir -p $GITHUB_WORKSPACE/install/lib/cmake
        mkdir -p $GITHUB_WORKSPACE/install/include
    - name: Cache IODA
      id: cache-ioda
      uses: actions/cache@v5
      with:
        path: |
          ${{ github.workspace }}/install
        key: ${{ runner.os }}-ioda-${{ steps.dep-hashes.outputs.ioda }}
    - name: Show me things
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE
        pwd
        ls -l
        ls -l i-jedi
        ls -l i-jedi/bundle
        ls -l Build
        ls -l install || true

    - name: Run ecbuild
      shell: bash
      run: |
        # Use root to avoid permission issues in GITHUB_WORKSPACE
        export jedi_cmake_ROOT=/opt/view
        source /opt/spack-environment/activate.sh
        cd $GITHUB_WORKSPACE
        mkdir -p Build
        cd Build
        export IJEDI_MPI_ARGS="--map-by :OVERSUBSCRIBE"

        if [[ "${{ steps.cache-ioda.outputs.cache-hit }}" == "true" ]]; then
          echo "Using cached IODA"
          ecbuild -DBUILD_IODA=OFF -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/install -DCMAKE_PREFIX_PATH=$GITHUB_WORKSPACE/install ../i-jedi/bundle
        else
          echo "Building IODA from source"
          ecbuild -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/install ../i-jedi/bundle
        fi

    - name: Compile the code
      shell: bash
      run: |
        export jedi_cmake_ROOT=/opt/view
        source /opt/spack-environment/activate.sh
        cd $GITHUB_WORKSPACE/Build
        make -j4
        make install
    - name: Verify installation
      shell: bash
      run: |
        ls -R $GITHUB_WORKSPACE/install
